"""additional fields added to user model

Revision ID: 445a3f251007
Revises: b85ce60d1b89
Create Date: 2024-11-25 01:55:21.791757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445a3f251007'
down_revision = 'b85ce60d1b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=False))
        batch_op.alter_column('user_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.alter_column('user_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
