"""empty message

Revision ID: cfce0a9a7d75
Revises: 5f0778629725
Create Date: 2024-11-26 08:28:27.098777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfce0a9a7d75'
down_revision = '5f0778629725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_login_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('last_login_ip', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('login_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
